spring.application.name= travel-agency-management-system-api

spring.datasource.url= jdbc:mariadb://localhost:3306/travelagency
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate